[package]
name = "puzzles"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
csbindgen = { path = "../csbindgen" }
bitflags = "2.1.0"

[build-dependencies]
cc = "1.0.79"
bindgen = "0.69.4"
csbindgen = { path = "../csbindgen" }
